// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgkyv0WiOpb9HMTVxflptWdZwjo-1ZpQ8',
    appId: '1:1071191691448:web:5e0d738b9b836682ad244d',
    messagingSenderId: '1071191691448',
    projectId: 'skillcast-71f39',
    authDomain: 'skillcast-71f39.firebaseapp.com',
    storageBucket: 'skillcast-71f39.firebasestorage.app',
    measurementId: 'G-374VNRKTWD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqJGURObhUYureCx1GasD8Ze9wskwPyVQ',
    appId: '1:1071191691448:android:b2691bd5d8eda480ad244d',
    messagingSenderId: '1071191691448',
    projectId: 'skillcast-71f39',
    storageBucket: 'skillcast-71f39.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMmhdKayAo-crOMCDRGiAoSAvdHrKKJbo',
    appId: '1:1071191691448:ios:96115b2bdc4e7361ad244d',
    messagingSenderId: '1071191691448',
    projectId: 'skillcast-71f39',
    storageBucket: 'skillcast-71f39.firebasestorage.app',
    iosBundleId: 'com.example.skillcast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMmhdKayAo-crOMCDRGiAoSAvdHrKKJbo',
    appId: '1:1071191691448:ios:96115b2bdc4e7361ad244d',
    messagingSenderId: '1071191691448',
    projectId: 'skillcast-71f39',
    storageBucket: 'skillcast-71f39.firebasestorage.app',
    iosBundleId: 'com.example.skillcast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgkyv0WiOpb9HMTVxflptWdZwjo-1ZpQ8',
    appId: '1:1071191691448:web:248db1adf82734bfad244d',
    messagingSenderId: '1071191691448',
    projectId: 'skillcast-71f39',
    authDomain: 'skillcast-71f39.firebaseapp.com',
    storageBucket: 'skillcast-71f39.firebasestorage.app',
    measurementId: 'G-Y4TM887WJ9',
  );
}
